
development:
  adapter: postgresql
  encoding: unicode
  database: ono_burrito_development
  pool: 5
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ono_burrito_test
  pool: 5
  username:
  password:
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: ono_burrito_production
  pool: 5
  username:
  password:
  host: localhost

